services:
  mysql:
    image: mysql:8.4
    container_name: seat-reservation-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: seat_reservation
      MYSQL_USER: seat_user
      MYSQL_PASSWORD: seat_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
	
	app:
	  jwt:
	    secret: "this_is_secret_key_12345678901234567890"
	    expiration: 8640000

		management:
		  endpoints:
		    web:
		      exposure:
		        include: health,info,metrics,prometheus

		  endpoint:
		    health:
		      show-details: always

		  metrics:
		    tags:
		      application: seat-reservation