spring.application.name=seat-reservation

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/seat_reservation}
spring.datasource.username=${DB_USERNAME:seat_user}
spring.datasource.password=${DB_PASSWORD:seat_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# Flyway Logs
#logging.level.org.flywaydb=INFO

# JWT Configuration
app.jwt.secret=${JWT_SECRET:this_is_secret_key_12345678901234567890}
app.jwt.expiration=${JWT_EXPIRATION:3600000}

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Application Metrics Tag
management.metrics.tags.application=seat-reservation

# Server Port
server.port=${PORT:8080}